### ISSUE TITLE
DownloadDistmapResult does not handle correctly PG in records

### ISSUE THREAD

**Issue by magicDGS** [magicDGS/ReadTools#396]
As described by @robmaz in https://github.com/magicDGS/ReadTools/issues/394#issuecomment-361954765, while downloading files with `PG` tags included in the records but removing the header lines, the tag is maintained and thus is breaking the output file.

This was not picked before because the bwa test files does not include the tag in the records, but for example novoalign does. This should be fixed and a text included, doing a point-release for the fix.

**Comment by magicDGS** [comment]
There is an example file uploaded in https://github.com/magicDGS/ReadTools/issues/394#issuecomment-361954765 that might be useful to check the issue.

**Comment by magicDGS** [comment]
@robmaz, can you upload to this issue three files coming from different parts with the first 50 lines each? That will be perfect for testing!

Thanks in advance!

**Comment by robmaz** [comment]
Here are some test files:




[part-00000.gz](https://github.com/magicDGS/ReadTools/files/1682745/part-00000.gz)
[part-00001.gz](https://github.com/magicDGS/ReadTools/files/1682746/part-00001.gz)
[part-00002.gz](https://github.com/magicDGS/ReadTools/files/1682747/part-00002.gz)

**Comment by magicDGS** [comment]
Thanks for the data, it was so useful for adding the tests.
