### ISSUE TITLE
TrimAdapters support for distmap upload

### ISSUE THREAD

**Issue by robmaz** [magicDGS/ReadTools#405]
Relates to #310 and to a discussion we had recently. It would be nice to both have the feature of trimming remainders of technical sequences, and also the option to turn trimmed bases into N in the fastq records instead of clipping them.

**Comment by magicDGS** [comment]
I don't understand the "the feature of trimming remainders of technical sequences" part of the issue.

For the others:

* Adapter trimming, as you pointed out, is a duplicate issue with #310 (whenever a trimmer is implemented, there is automatic support for distmap upload thanks to the plugin)
* Turn the trimmed bases into N in the records (or soft-clip if it is a mapped SAM/BAM file), is a duplicate of https://github.com/magicDGS/ReadTools/issues/358 (for distmap but also for trim reads).

**Comment by magicDGS** [comment]
If the sentence that I don't understand is not adding anything to that issues, you can close this one @robmaz 

If you really need this, I can add a high-priority label to the other issues.

**Comment by robmaz** [comment]
That just meant adapter trimming. I think those two would be major improvements. I am closing this issue here, since it's a duplicate.

**Comment by magicDGS** [comment]
@robmaz - I included in the repository a new project for Distmap integrations (https://github.com/magicDGS/ReadTools/projects/7). I will include in the project the issues related with it...just let me know the priority of each issue to add it to the correct column.
