### ISSUE TITLE
Use tag constants for store barcode/trimming information

### ISSUE THREAD

**Issue by magicDGS** [magicDGS/ReadTools#61]
In [`SAMTag`](https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/SAMTag.java) (definitions from the specs) and [`ReservedTagConstants`](https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/ReservedTagConstants.java) there are several useful tags for storing important information:
- `ReservedTagConstants.XT`: indicates where the read started to be clipped/trimming. This should be use in conjuction with another tag to indicate the end of clipping/trimming.
- `SAMTag.BC` and `SAMTag.QT`: barcode sequence and quality. This should be also be used in conjuction with a value for a second index (defined now as `B2`, I don't know about the QT). We should accept, with a warning, the deprecated `SAMTag.RT` for barcode sequence.

We should define our own constants for other information.

**Comment by magicDGS** [comment]
New support for "barcodes" (although I guess that it is regarding biological barcoding) are in this PR for SAM specs (https://github.com/samtools/hts-specs/pull/119)

In addition, about the separation of the indexes in Picard is an hyphen (https://github.com/broadinstitute/picard/pull/689), although it seems that is going to be implementation-specific, so we are fine.

**Comment by nh13** [comment]
@magicDGS "barcodes" can be used to identify a source molecule or set of molecules during the library prep and sequencing process.  See for example sample barcoding, 10x genomics, many folks using molecular identifiers to improve somatic mutation detection, and others.  I would urge you to use "hyphen" too.

**Comment by magicDGS** [comment]
@nh13, thanks for clarifying!

**Comment by magicDGS** [comment]
Because you participated here, @nh13, could you help me with a very stupid question? I'm talking here about sample-barcodes (__BC__ tag), and when multiplexing is done with dual indexing.

My purpose is to condense in the __BC__ tag (and/or the read name, for don't lose information after mapping a FASTQ files) the two indexes, because for instance [illumina2bam](http://gq1.github.io/illumina2bam/) uses a custom tag for the second barcode (`SECOND_BARCODE_SEQUENCE_TAG_NAME` argument) and we receive data with a __B2__ tag that I would like to avoid.

Do you think that the "hyphen" should be also used in this case? I'm currently using "underscore" for separate them, but because a major refactoring of this toolkit will break compatibility with previous versions anyway, I would like to solve this soon.

Thanks for the participation in the conversation, I really appreciate it!

**Comment by nh13** [comment]
You can store the assigned barcode in the read group (platform unit: flowcell-barcode.lane) for all the reads with that barcode. If you *really* want the "raw" index bases, then store those in the `BC` tag.  If you have reads who don't match an expected barcode, then I **would** store their raw barcode bases in the `BC` tag.  Folks are already using a hyphen as a delimiter: https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/util/IlluminaUtil.java#L212-L214
https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/illumina/ClusterDataToSamConverter.java#L214

**Comment by magicDGS** [comment]
Thanks for the explanation @nh13!

**Comment by magicDGS** [comment]
In the new framework the fixing for barcode encoding is already implemented (for other tags and/or encoded in the read name). The reads are normalized using the default tags `BC` (raw barcodes) and `QT` (barcode qualities). In addition, the hyphen separator is the default for the toolkit, but it is a settable JVM property to allow using custom separators if they prefer a different one. This brings more flexibility regarding personal taste, because the specs are not defining the separator yet.

Closing because the trimming tag issue will be tracked in the new design (#46).
